### ISSUE TITLE
Package spot for Debian

### ISSUE THREAD

**Issue by nodiscc** [rauchg/spot#26]
Leaving this as a reminder for myself.

I intend to package spot for Debian and derivatives. A Request For Packaging has been filed at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=688866

Of course, any help is welcome.

**Comment by kapouer** [comment]
Hi there, any progress on this ? This software is really cool and pretty easy to debianize.

**Comment by nodiscc** [comment]
@kapouer sorry I've had no time to work on this.

>pretty easy to debianize.

Is it? If you'd like to document the packaging process/send some links I'd be grateful because I'm not sure I understand how to do it really properly.

**Comment by kapouer** [comment]
Sure, it requires quite a bit of interaction, though. Ring me when you have some free time to spend on  this.
